### ISSUE TITLE
isf-client webgl error

### ISSUE THREAD

**Issue by northeastsquare** [mikrohash/isf-client#1]
Hello, Thank for your great iota project. And I met a problem, the page got error:
Uncaught Error: Unable to initialize WebGL. Your browser may not support it.
    at module.exports (curl.min.js:10344)
    at Object.WebGLWorker [as worker] (curl.min.js:10210)
    at Object.PearlDiverInstance [as instance] (curl.min.js:10474)
    at Object.init (curl.min.js:5646)
    at spammer.js:28
    at spammer.js:313
spamfund.js:8 Uncaught SyntaxError: Unexpected token )
jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'options' of undefined TypeError: Cannot read property 'options' of undefined
    at HTMLDocument.<anonymous> (file:///home/sam/pysrc/isf-client-0.2.3.3/js/main.js:32:27)
    at j (file:///home/sam/pysrc/isf-client-0.2.3.3/js/jquery.min.js:2:29999)
    at k (file:///home/sam/pysrc/isf-client-0.2.3.3/js/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Cannot read property 'options' of undefined
    at HTMLDocument.<anonymous> (main.js:32)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)

**Comment by vuapo-eth** [comment]
Yes this is a big issue because it happens on many PCs. Unfortunately it is directly connected to IOTAs curl library. I have no idea if there is an easy way to fix this.

We are thinking about creating a Java spammer which wouldn't have this problem. But we will probably not do that in the next weeks.
